version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd-server
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      ETCD_NAME: s1
      ETCD_DATA_DIR: /etcd-data
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_CLUSTER: s1=http://0.0.0.0:2380
      ETCD_INITIAL_CLUSTER_TOKEN: tkn
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_LOG_LEVEL: info
    volumes:
      - etcd-data:/etcd-data
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - etcd-network

  etcd-sample:
    build: 
      context: ../../
      dockerfile: samples/etcd/Dockerfile
    container_name: etcd-sample-app
    depends_on:
      etcd:
        condition: service_healthy
    environment:
      - ETCD_ENDPOINTS=etcd:2379
    networks:
      - etcd-network

volumes:
  etcd-data:

networks:
  etcd-network:
    driver: bridge